#!/bin/bash
if [ $# -eq 0 ];then
    cat CMakeLists.txt | grep executable | while read line ; do echo $line ; done 
    echo "give me name of executable"
    read file
else
    file=$1
fi
/usr/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/bin/gcc-9 -DCMAKE_CXX_COMPILER:FILEPATH=/bin/g++-9 -H/home/lpawlak/pi -B/home/lpawlak/pi/build -G "Unix Makefiles"
/usr/bin/cmake --build /home/lpawlak/pi/build --config Debug --target $file
echo "let's begin"
/home/lpawlak/pi/build/$file

